# Generated by Django 4.2.8 on 2024-01-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('symbol', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('market', models.CharField(blank=True, max_length=20, null=True)),
                ('sectorName', models.CharField(max_length=25)),
                ('sectorSymbol', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Ohlcv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(max_length=8)),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicatorapp.item')),
            ],
        ),
    ]
