# Generated by Django 4.2.8 on 2024-01-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorapp', '0002_alter_ohlcv_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohlcv',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
