# Generated by Django 4.2.8 on 2024-01-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorapp', '0003_alter_ohlcv_close_alter_ohlcv_high_alter_ohlcv_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohlcv',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
