# Generated by Django 4.2.8 on 2024-01-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorapp', '0004_alter_ohlcv_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ohlcv',
            old_name='close',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='ohlcv',
            old_name='high',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='ohlcv',
            old_name='low',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='ohlcv',
            old_name='open',
            new_name='Open',
        ),
        migrations.RenameField(
            model_name='ohlcv',
            old_name='volume',
            new_name='Volume',
        ),
    ]
