# Generated by Django 4.2.8 on 2024-02-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorapp', '0005_rename_close_ohlcv_close_rename_high_ohlcv_high_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='USBureauEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
        ),
    ]
