# Generated by Django 4.2.8 on 2024-03-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorapp', '0006_usbureauevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('market_cap', models.IntegerField(blank=True, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('net_income', models.IntegerField(blank=True, null=True)),
                ('net_debt', models.IntegerField(blank=True, null=True)),
                ('EBITDA', models.IntegerField(blank=True, null=True)),
                ('cost_and_expenses', models.IntegerField(blank=True, null=True)),
                ('depreciation_and_amortization', models.IntegerField(blank=True, null=True)),
                ('total_current_assets', models.IntegerField(blank=True, null=True)),
                ('total_current_liabilities', models.IntegerField(blank=True, null=True)),
                ('total_non_current_liabilities', models.IntegerField(blank=True, null=True)),
                ('cash_flow_from_operations', models.IntegerField(blank=True, null=True)),
                ('cash_flow_from_investing', models.IntegerField(blank=True, null=True)),
                ('cash_flow_from_financing', models.IntegerField(blank=True, null=True)),
                ('cash_beginning_of_period', models.IntegerField(blank=True, null=True)),
                ('cash_end_of_period', models.IntegerField(blank=True, null=True)),
                ('gross_profit_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('EBITDA_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('operating_income_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('net_income_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('earnings_yield', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('return_on_capital', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
            ],
        ),
    ]
