# Generated by Django 4.2.8 on 2024-03-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorapp', '0007_financialstatement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialstatement',
            name='earnings_yield',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='return_on_capital',
        ),
    ]
