# Generated by Django 4.2.8 on 2024-03-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorapp', '0008_remove_financialstatement_earnings_yield_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialstatement',
            name='date',
        ),
    ]
