# Generated by Django 4.2.8 on 2024-03-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorapp', '0010_financialstatement_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
