# Generated by Django 4.2.8 on 2023-12-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_btcusdt_15m'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='btcusdt_15m',
            new_name='btcusd',
        ),
    ]
