# Generated by Django 4.2.8 on 2024-01-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='epsActual',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='epsEstimate',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hour',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='quarter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='revenueActual',
            field=models.DecimalField(decimal_places=1, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='revenueEstimate',
            field=models.DecimalField(decimal_places=1, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='symbol',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
