# Generated by Django 4.2.8 on 2024-01-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_remove_event_description_remove_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='epsActual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='epsEstimate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hour',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='quarter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='revenueActual',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='revenueEstimate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True),
        ),
    ]
