# Generated by Django 4.2.8 on 2024-01-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_alter_event_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='revenueActual',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='revenueEstimate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
    ]
