# Generated by Django 4.2.8 on 2024-01-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_alter_event_revenueactual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='epsActual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='epsEstimate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
