# Generated by Django 4.2.8 on 2024-02-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_alter_event_epsactual_alter_event_epsestimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='event',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='event',
            name='revenueActual',
        ),
        migrations.RemoveField(
            model_name='event',
            name='revenueEstimate',
        ),
        migrations.AddField(
            model_name='event',
            name='epsSurprisePct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
