# Generated by Django 4.2.8 on 2024-02-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoAnalysis',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.DeleteModel(
            name='PressRelease',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Site URL'),
        ),
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
