# Generated by Django 4.2.8 on 2024-02-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_delete_cryptoanalysis_delete_editorial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='abstract',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='datetime',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='link',
        ),
        migrations.RemoveField(
            model_name='article',
            name='media',
        ),
        migrations.AddField(
            model_name='article',
            name='byline',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='headline',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='lead_paragraph',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='news_desk',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='print_page',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='print_section',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='section_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='snippet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='subsection_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='web_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Site URL'),
        ),
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
