# Generated by Django 4.2.8 on 2024-02-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_rename_title_article_abstract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='print_page',
        ),
        migrations.RemoveField(
            model_name='article',
            name='print_section',
        ),
        migrations.AddField(
            model_name='article',
            name='neg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='neu',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
