# Generated by Django 4.2.8 on 2024-02-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_remove_article_print_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='byline',
        ),
    ]
